version: '3.8'

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    networks:
      - app-network

  app:
    build:
      context: ./url-backend
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2181
    volumes:
      - app_data:/data
    depends_on:
      - zookeeper
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  app_data:

networks:
  app-network: